/*
* action的type常量模块
*
* */
export const SAVE_USER = 'SAVE-USER';
export const REMOVE_USER= 'REMOVE_USER';
export const SET_TITLE= 'SET_TITLE';
export const GET_CATEGORIES_SUCCESS= 'GET_CATEGORIES_SUCCESS';
export const ADD_CATEGORIES_SUCCESS= 'ADD_CATEGORIES_SUCCESS';
export const UPDATE_CATEGORIES_SUCCESS= 'UPDATE_CATEGORIES_SUCCESS';
export const DELETE_CATEGORIES_SUCCESS= 'DELETE_CATEGORIES_SUCCESS';
